In [ ]:
import cv2
import numpy as np
src = cv2.imread("plane.png" , 0)

dst = cv2.equalizeHist(src)
cv2.imshow('Source image', src)
cv2.imshow('Equalized Image', dst)

##cv2.imwrite('RGBY.png',res)

cv2.waitKey(0)
cv2.destoryAllwindows()

In [ ]:
import cv2 as cv
import numpy as np

frame98 = cv.imread("frame98.jpg")
frame98 = cv.resize(frame98 , None , fx = 0.4 , fy = 0.4)
#print(frame98[1,:,:])


cv.imshow("original" , frame98)
#frame98[:,:,0] = 0
print(frame98.shape)
gray = cv.cvtColor(frame98  , cv.COLOR_BGR2GRAY)
print(frame98[:,:,0])
dst = cv.equalizeHist(gray)

cv.imshow("equalized" , dst)
cv.imshow("without blue" , frame98)


cv.waitKey(0)
cv.destroyAllWindows()


(432, 688, 3)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
import cv2 as cv
import numpy as np

frame98 = cv.imread("frame98.jpg")
frame98 = cv.resize(frame98 , None , fx = 1 , fy = 1)


blur = cv.GaussianBlur(frame98,(5,5),0)
# hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# yellownMask = cv2.inRange(hsv, (20,120,255), (40,255,255))
# hsv[:,:,1] = yellownMask 
# back = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

# img = cv2.imread("D:\\testing\\test.png",1)

#you must notice that now the images in hsv format
hsv = cv.cvtColor(blur, cv.COLOR_BGR2HSV)
greenMask = cv.inRange(hsv, (26, 10, 30), (97, 100, 255))

frame98[greenMask == 255] = (0, 255, 0)

cv.imshow("result" , frame98)
cv.imshow("greenMask" , greenMask)


cv.waitKey(0)
cv.destroyAllWindows()