In [ ]:
import numpy as np
import cv2
img = cv2.imread("Cat.jpg",1) #as color scal here
img = cv2.resize(img , None , fx = 0.3 , fy = 0.3 )
cv2.imshow("original image",img)
rows,colms,channels = img.shape   #we must notice that when we get image at gray scal the img.shape will not return channels
print(img.shape)
translation_matrix = np.float32([[1,0,50],[0,1,-70]])
print(translation_matrix)
translated_image = cv2.warpAffine(img , translation_matrix, (colms,rows))
cv2.imshow("translated image",translated_image)
cv2.waitKey(0)
cv2.destroyAllwindows()

(539, 802, 3)
[[  1.   0.  50.]
 [  0.   1. -70.]]


In [ ]:
import cv2
import numpy as np

img = cv2.imread("Cat.jpg" , 1)
img = cv2.resize(img , None , fx  = 0.3 , fy = 0.3)
cv2.imshow("Original" , img)
rows,colms,channels = img.shape
transformation_points1 = np.float32([[50 , 50 ],[ 200 , 50 ],[ 50 , 200]])#those points must be fare from each other and from a triangle
transformation_points2 = np.float32([[10 , 100 ],[ 200 , 100 ],[ 100 , 250]])#those points must be fare from each other and from a triangle
matrix = cv2.getAffineTransform(transformation_points1,transformation_points2)
print(matrix)
transformed_image = cv2.warpAffine(img, matrix , (colms,rows))
cv2.imshow("transformed_image" ,transformed_image )
cv2.waitKey(0)
cv2.destoryAllwindows()


[[ 1.26666667e+00  6.00000000e-01 -8.33333333e+01]
 [-7.10542736e-17  1.00000000e+00  5.00000000e+01]]


In [ ]:
import cv2
import numpy as np

img = cv2.imread("cards.jpg",1)
cv2.imshow("Original image",img)
width,height = [250,350]
# we need to know the three points of the card edges and transform to 2D image
edges_points = np.float32([[367,350],[577,338],[400,660],[643,640]]) #to get this point open image on paint the coordinated are on the bottom of screen
new_edges_points = np.float32([[0,0] , [width,0] , [0,height],[width,height]])
matrix = cv2.getPerspectiveTransform(edges_points,new_edges_points)
out_image = cv2.warpPerspective(img , matrix , (width , height))
for x in range(0,4):
    cv2.circle(img,(edges_points[x][0] , edges_points[x][1]),5,[0,0,255],cv2.FILLED)

cv2.imshow("Circle image",img)
cv2.imshow("Outout image",out_image)

cv2.waitKey(0)
cv2.destoryAllwindows()


In [1]:
import cv2
import numpy as np

img = cv2.imread("cat.jpg",0)
img = cv2.resize(img,None,  fx = 0.3 , fy = 0.3 )
rows,colms = img.shape
M = cv2.getRotationMatrix2D((colms/2, rows/2) , 90 , 1)
dst = cv2.warpAffine(img , M , (colms, rows))
cv2.imshow("dst" , dst)

cv2.waitKey(0)
cv2.destroyAllWindows()
